check if crypto is defined (#233)
* check if crypto is defined

if we don't check if crypto is defined or not.
it gives the following error.

```
ReferenceError: crypto is not defined
```

* Add a changeset

---------

Co-authored-by: Sunil Pai <threepointone@gmail.com>