check if crypto is defined
if we don't check if crypto is defined or not.
it gives the following error.

```
ReferenceError: crypto is not defined
```